[PR#14] Register 관련 View 구현
Team-PLAT/Plat-iOS pull request #16
Opened 2024-07-10 07:38 UTC by crownjoe

close #14 

## *⛳️ Work Description*
- OnboardingView 구현
- LoginView 구현
- SelectStreamAccountView 구현
- 디자인 시스템 Image 추가
- 디자인 시스템 Lottie Json 추가

## *📸 Screenshot*
|기능|스크린샷|
|:--:|:--:|
|ex)로그인|<img width="250" alt="AppFlow" src="https://github.com/Team-PLAT/Plat-iOS/assets/113565086/e624fb82-8dfb-4c5b-a148-23f920877c73">|

## *📢 To Reviewers*
- 작업중입니다

## *✅ Checklist*
- [ ] 주석 및 프린트문 제거 확인.
- [ ] 컨벤션 준수 확인.

2024-07-13 05:57 UTC, crownjoe commented on PLAT/PLAT/Data/LoginService.swift
> +        request.requestedScopes = [.fullName, .email]
애플 로그인을 진행할 때 `로그인 요청 호출`,` 로그인 완료 후 호출 ` 두 함수만 필요하여서 로그인, 회원가입으로 나누기 보다는 해당 함수 들로 로그인 서비스 코드를 작성하였습니다.

2024-07-13 05:57 UTC, crownjoe commented on PLAT/PLAT/Data/LoginService.swift
> +//                let authorizationCode = String(data: appleIDCredential.authorizationCode!, encoding: .utf8)
다양한 정보를 불러올 수 있는데 API 명세서 정확히 나오고 나면 진행하려고 우선 주석 처리 해두었습니다!

2024-07-13 05:57 UTC, crownjoe commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +}
요 부분은 후에 UI가 변경될 예정이라 감안하고 봐주세요!
톨털팀에서 정책 보기 코드들 작성해주신 것 가져다가 썼습니다 ㅎ.ㅎ 👍

2024-07-13 09:51 UTC, thinkySide requested changes
코드 리뷰 남겨두었습니다! 확인 부탁드립니다!

2024-07-13 09:51 UTC, thinkySide commented on PLAT/PLAT/Domain/Interface/LoginServiceInterface.swift
> +    func handleLogin(_ authResult: Result<ASAuthorization, Error>) -> Result<Bool, Error>
~~~swift
/// 로그인 요청하기
func requestLogin() {
    loginService.requestLogin(ASAuthorizationAppleIDProvider().createRequest())
}
~~~

`requestLogin` 함수의 인자인  `_ request: ASAuthorizationAppleIDRequest` 는 빠져도 될 것 같습니다!

UseCase의 목적을 생각했을 때, UseCase는 애플 로그인이 어떻게 구현되는지에 대해 알지 못해야 하기 때문에 인터페이스에서도 정의되면 본래의 의도와 벗어날 수 있을 것 같아요!

바로 아래 `handleLogin`의 경우에도 애플 로그인과 관련된 것들이 빠져야할 것 같긴하지만,,, 요 부분은 지금 당장 빼기는 어려워 보입니다. (SwiftUI의 View에서 곧바로 `Result<ASAuthorization, any Error>` 타입을 내려주고 있기 때문에 완벽한 분리가 어려울 듯 합니다.)

결론적으로 구체적인 것에 의존하는 것을 최대한 걷어낼 수 있는 방향으로 구조를 잡아갈 수 있으면 하기에 위와 같은 내용 요청드립니다!

2024-07-13 09:51 UTC, thinkySide commented on PLAT/PLAT/Domain/UseCase/LoginUseCase.swift
> +import AuthenticationServices
바로 위 코멘트에서 말씀드린 내용처럼, UseCase는 도메인 계층으로서 구체적인 것(애플 로그인 등)에 의존하지 않는 방향이 본래의 목적이라고 할 수 있을 것 같아요!

하지만 SwiftUI의 특성상 완전히 걷어내기는 힘들어보이기 때문에 우선 이렇게 작업하고, 추후 다같이 논의해보면 좋을 것 같아요!

2024-07-13 09:51 UTC, thinkySide commented on PLAT/PLAT/Domain/UseCase/LoginUseCase.swift
>      }
위에서 이야기한 내용과 이어집니다!

`ASAuthorizationAppleIDProvider().createRequest()` 해당 구문은 구현체인 LoginService에서 작성해도 될 것 같아요!

2024-07-13 09:51 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +}
전역적으로 사용될 것 같은 enum 타입은 파일을 따로 생성해 관리하는 것이 좋을 것 같습니다! (관리에 용이함을 더하기 위해)

우선 Entity 폴더 내 파일을 생성해 관리해보면 어떨까 제안드립니다!

2024-07-13 09:51 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +// MARK: - SignUpView
사소한 부분이긴 하지만, MARK 주석 사용 시에 컨벤션을 통일하고 싶어서요! 다른 분들의 의견이 듣고 싶습니당!
@crownjoe @Junu-Park @WooFeather 

1. 바로 하단 코드와 붙이기
~~~swift
// MARK: - ContentView
struct ContentView: View {
    // some view...
}
~~~

2. 바로 하단 코드에서 한 줄 띄우기
~~~swift
// MARK: - ContentView

struct ContentView: View {
    // some view...
}
~~~

여러분의 의견이 듣고 싶습니당!!

2024-07-13 09:51 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +            Image("headphone")
이전 Xcode 업데이트로 해당 부분은 아래와 같이 사용될 수 있어 제안드립니다!

~~~swift
Image(.headphone)
~~~

위와 같이 사용했을 때의 장점은 다음과 같습니다.
1. 자동 완성 기능 사용 가능
2. 파일명이 달라졌을 때의 컴파일 에러
3. 문자열이 잘못 입력되었을 때의 휴먼 에러 방지

2024-07-13 09:51 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +                }
요런 부분들은 나중에 에러처리를 할 수 있게 Error 타입을 미리 정의해두는 것도 좋을 것 같습니다! (우선순위 상으로는 낮지만, 추후 꼭 필요한 내용이니 리마인드 차원에서 코멘트 남깁니당)

2024-07-13 18:09 UTC, Junu-Park commented on PLAT/PLAT/Resource/Assets.xcassets/headphone.imageset/Contents.json
>        "filename" : "headphone.png",
headphone svg 파일은 전달 받았으나 깨져있어서 아직 교체하지 않았습니다.

2024-07-13 18:10 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +                .frame(height: 20)
높이를 20으로 고정해야할지 얘기가 필요하지 않을까 생각이 들었습니다!

2024-07-13 18:13 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +}
Text의 특정 문자만 다른 모디파이어를 적용해야하는 경우에 사용할 수 있는 Text extension입니다.

2024-07-13 18:18 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +    }
스트리밍계정 선택 상태에 대한 열거형입니다.
(none = 초기 진입 시, 아무 스트리밍계정도 선택되지 않은 상태)

2024-07-13 18:18 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +    @State var selectedState: SelectedState = .none
스트리밍계정 선택 상태 관리를 위한 변수입니다.

2024-07-13 18:20 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            }
ListRadioButton 컴포넌트를 사용했고 Group으로 묶어서 같은 모디파이어를 적용시켰습니다.

2024-07-13 18:21 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            }
SelectStreamAccountView에서는 스트리밍계정 선택 버튼이 테두리가 있어서 적용시켰습니다.

2024-07-13 18:24 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +        .presentationDetents([.fraction(0.3)])
sheet의 height를 화면의 30%로 적용했으나 figma와 다소 다르게 표시되기에 논의가 필요한 것 같습니다.

2024-07-13 18:26 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Component/ListRadioButton.swift
> +                .frame(width: 24, height: 24)
spotify 이미지를 바꾸면서 이전과 달리 크기가 맞지 않아서 프레임 크기를 주어서 고정시켰습니다.

2024-07-13 18:27 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +// MARK: - SignUpView
둘 다 상관은 없으나, 현재 저도 2번 방식을 적용하긴 했습니다!

2024-07-13 18:33 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +            Image("headphone")
이게 가능한지 몰랐네요! 문자열보다 좋은거 같아요~!
LGTM👍

2024-07-14 02:19 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +}
오오! extension으로 만들어둬서 추후 다양하게 적용이 가능할 것 같습니다!!! 굳굳

2024-07-14 02:19 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +                .frame(height: 20)
오 정확히 어떤 부분이죠?

2024-07-14 02:22 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            }
좋은 것 같습니다! 유지보수 측면에서 요렇게 Group으로 묶어주는게 좋은 것 같아유.

2024-07-14 02:25 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +}
++ 추가로 Extension의 경우 코드 분리를 위해  파일을 Helper 폴더에 생성하는 것이 어떨까 제안드립니다!

2024-07-14 02:31 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            })
요것도 컨벤션 관련이라 여러분들 의견을 여쭙고 싶어 코멘트 남겨봅니다!!
@crownjoe @Junu-Park @WooFeather 

1번 방식(기존)
~~~swift
Button(action: {
    isSheetPresented.toggle()
    print("왜 스트리밍 계정을 연결하나요?")
}, label: {
    Text("왜 스트리밍 계정을 연결하나요?")
        .font(.Body.body4)
        .underline()
})
.padding(.horizontal, 108)
.padding(.bottom)
~~~

2번 방식
~~~swift
Button {
    isSheetPresented.toggle()
    print("왜 스트리밍 계정을 연결하나요?")
} label: {
    Text("왜 스트리밍 계정을 연결하나요?")
        .font(.Body.body4)
        .underline()
}
.padding(.horizontal, 108)
.padding(.bottom)
~~~

팀원 분들의 의견이 듣고 싶습니당!

2024-07-14 02:32 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            })
++ 이와 관련된 `trailing closure`를 어떻게 사용할 것인지에 대해 이야기하는 것도 좋을 것 같네요!!

2024-07-14 03:06 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +                .frame(height: 20)
`OnboardingView`에서 최상단에 있는 'PLAT' 이미지 입니다!
figma에서 `height`가 20으로 되어있어서 일단 20으로 고정하긴 했는데 고정하는게 맞는지 생각이 드네요?

2024-07-14 03:09 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            }
이번에 `Group`에 대해 알게 돼서 활용해봤는데 좋은거 같네요!!

2024-07-14 03:12 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +}
저도 그게 좋을 것 같네요!
옮겨 놓도록 하겠습니다~!!
감사합니다

2024-07-14 03:13 UTC, thinkySide commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +                .frame(height: 20)
넵 방금 Xcode로 확인해봤는데 고정해도 좋을 것 같습니다 저는!!!

2024-07-14 03:27 UTC, Junu-Park commented on PLAT/PLAT/Helper/Helper+Text.swift
> +}
`OnboardingView`file에서 Text extension 제거 후
`Helper+Text`file 생성해서 이동 시켰습니다!

2024-07-14 03:51 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            })
저는 `Button`의 경우에는 의도하지는 않고 자동으로 생성되는 1번 방식으로 주로 사용했었습니다!
`trailing closure`에 대한 이해도가 높지는 않지만 단축 인자를 추가적으로 사용하는 등 사용 방법이 다양해서 통일성이 필요할 것 같습니다!

2024-07-15 00:14 UTC, WooFeather commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +// MARK: - SignUpView
2번이 가독성이 더 좋아보여서 저는 2번을 적용했습니다

2024-07-15 00:15 UTC, WooFeather commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +            Image("headphone")
오 너무 좋은데요?? 감사합니다 👍

2024-07-15 00:19 UTC, WooFeather commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            })
저는 더 깔끔한 방식이라 2번을 주로 사용했었습니다.

2024-07-15 04:20 UTC, Junu-Park commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +                .frame(height: 20)
넵! 알겠습니다!

2024-07-15 07:36 UTC, WooFeather approved these changes
컨벤션 통일과 각종 인사이트가 많이 나온 좋은 코드리뷰였습니다!
LGTM!!

2024-07-15 07:39 UTC, crownjoe reviewed
굿굿!!! 하나하나 잘 맞춰가봅시다요~~~~~~🙉

2024-07-15 07:39 UTC, crownjoe commented on PLAT/PLAT/Domain/Interface/LoginServiceInterface.swift
> +    func handleLogin(_ authResult: Result<ASAuthorization, Error>) -> Result<Bool, Error>
아!! 그렇네요, use case 목적을 생각하면 빠지는 게 맞는 것 같습니다. 코리 반영해서 수정하도록 하겠습니다!!

2024-07-15 07:39 UTC, crownjoe commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +// MARK: - SignUpView
저도 1번 방식을 사용하긴 했는데 둘 다 괜찮습니다!

2024-07-15 07:39 UTC, crownjoe commented on PLAT/PLAT/Presentaion/Register/LoginView.swift
> +            Image("headphone")
오호라! 수정하겠습니다~.~ 감사합니당!

2024-07-15 07:39 UTC, crownjoe commented on PLAT/PLAT/Presentaion/Component/LottieAnimationView.swift
> +}
온보딩, 로그인 뷰에서 필요하여서 컴포넌트로 따로 빼두었습니다~!!

2024-07-15 07:39 UTC, crownjoe commented on PLAT/PLAT/Presentaion/Register/SelectStreamAccountView.swift
> +            })
저도 아서처럼 자동 생성되는 방식인 1번을 주로 사용했었습니다!_! trailing closure 요 부분도 이야기해보아야 할 것 같아요!

2024-07-15 07:39 UTC, crownjoe commented on PLAT/PLAT/Domain/Path/Path.swift
> +}
`RegisterPath` 경로 따로 만들어서 추가했습니다!

2024-07-15 07:39 UTC, crownjoe commented on PLAT/PLAT/Presentaion/Register/OnboardingView.swift
> +        } .environment(pathModel)
case 별로 path 추가해주었습니다!

2024-07-16 00:17 UTC, thinkySide approved these changes

2024-07-16 00:18 UTC, thinkySide commented
첫 프로그래밍 서로 잘 마친 것 같아 좋네요! LGTM!

2024-07-16 00:18 UTC, merged