[PR/#69] 트랙 API 연결
Team-PLAT/Plat-iOS pull request #72
Opened 2024-09-07 07:49 UTC by WooFeather

close #69

## *⛳️ Work Description*
-트랙API 관련 폴더링을 정리했습니다.
-API별로 파일 분류를 하겠습니다.
-Service그룹 내에 TrackService / MemberService로 분리하고 그 안에서 련 API처리를 다 하겠습니다.

## *📸 Screenshot*
|기능|스크린샷|
|:--:|:--:|
|ex)로그인|<img width="250" alt="AppFlow" src="https://github.com/Team-PLAT/Plat-iOS/assets/113565086/e624fb82-8dfb-4c5b-a148-23f920877c73">|

## *📢 To Reviewers*
-

## *✅ Checklist*
- [ ] 주석 및 프린트문 제거 확인.
- [ ] 컨벤션 준수 확인.

2024-09-07 07:50 UTC, WooFeather commented on PLAT/PLAT/Network/Service/DTO/BaseResponse.swift
> +    let timeStamp: String
BaseResponse의 timeStamp 오타 수정했습니다

2024-09-07 07:51 UTC, WooFeather commented on PLAT/PLAT/Network/Service/DTO/TrackDetail/TrackDetailAPI.swift
> +}
request와 response를 한 파일에서 관리하도록 수정했습니다.

2024-09-07 07:53 UTC, WooFeather commented on PLAT/PLAT/Network/Service/TrackFeedService.swift
> +        let url = APIs.Plat.Tracks.fetchFeed.url
url부분 한톨이 만들어준 엔드포인트 관리객체로 변경하였습니다(아래 동일)

2024-09-07 07:54 UTC, WooFeather commented on PLAT/PLAT/Network/Service/TrackFeedService.swift
> +    func postTrackFeed(request: TrackDetailRequest) async {
파라미터명을 requset로 수정하였습니다
(나머지도 수정에정)

2024-09-07 07:57 UTC, WooFeather commented on PLAT/PLAT/Network/Service/TrackMapService.swift
> +    }
URLComponents를 통해 쿼리파라미터로 url을 적용해서 넘겨주는 부분입니다.

2024-09-07 10:15 UTC, WooFeather commented on PLAT/PLAT/Network/Service/TrackService.swift
Track API와 관련된 Service는 한곳에 모아두었습니다.

2024-09-08 08:19 UTC, thinkySide requested changes
코멘트 달아두었고 옵셔널 바인딩 관련 수정 요청드렸습니다!

2024-09-08 08:19 UTC, thinkySide commented on PLAT/PLAT/Network/Service/TrackService.swift
> +struct TrackService {
최근 네트워크와 관련된 객체를 struct와 class 어떤걸로 구현해야하는가,,,에 대한 고민이 많아진 것 같습니다.
검색 중 고려하면 좋을 사항들이 정리된 stackOverflow 게시글을 찾아 공유드립니다!
https://stackoverflow.com/questions/68987329/struct-enum-vs-class-for-network-calls

- static 함수를 사용하지 마세요. 테스트하기 더 어려워집니다. Dependency Injection을 사용할 수 있지만, 개인적으로는 API 호출을 하는 서비스를 해결하는 것을 선호합니다. (저는 항상 인스턴스를 생성해야하나? 라는 생각때문에 static으로 만들곤 했는데, 다시금 생각하게 되는 문장인 것 같습니다. 결국 어디서든 접근이 가능해지기 때문에 시간이 지날수록 결합도가 과하게 높아질 수도 있다는 측면에서 주의깊게 생각해봤으면 합니다!)

- 프로토콜을 사용하면 테스트가 더 쉬워지고, 테스트를 생성할 수도 있습니다.

- 무언가를 호출하고 결과를 전달하기만 하면 되는 경우에는 struct로도 가능합니다.

- 인스턴스를 자주 전달해야 하는 경우 클래스가 구조체보다 더 나을 가능성이 큽니다. (요것도 기존의 생각을 다시 하게 만드는 문장인 것 같습니다. struct가 빠르다고 해서 무작정 선택해야하는 것은 아니라는 것을 다시금 느끼는 것 같습니다!)

- 로직에서 데이터베이스에 데이터를 넣어야 하는 경우, 데이터 페칭과 데이터 저장을 모두 수행한다면, 대부분 클래스를 사용해야 할 것입니다. 심지어 struct도 self를 변형하지 않으면 작동할 것입니다. 캡처 목록에 데이터베이스 서비스를 추가할 수 있습니다.

- **일관성을 유지하세요.** (요게 제일 중요한 포인트 같습니다!)

2024-09-08 08:19 UTC, thinkySide commented on PLAT/PLAT/Network/Service/TrackService.swift
> +        let authToken = "tokenishere"
요 토큰은 나중에 NetworkClient에서 모두 관리될 예정이라 머지 후에 수정이 필요합니다! (다른 함수도 동일)

2024-09-08 08:19 UTC, thinkySide commented on PLAT/PLAT/Network/Service/TrackService.swift
> +        let response: Result<BaseResponse<FetchTrackMapResponse>, Error> = await client.get(url: urlComponet!.url!, authToken: authToken)
startLatitude, startLogitude와 같은 값을 문자열로 직접 넣고 있기도 하고, 값에 이상이 생기면 현재 코드는 런타임 에러로 앱이 강제 종료 됩니다. (강제 언래핑!!) 옵셔널 바인딩 처리를 요청드립니닷

2024-09-08 08:19 UTC, thinkySide commented on PLAT/PLAT/Network/Service/TrackService.swift
> +        let response: Result<BaseResponse<FetchTrackFeedResponse>, Error> = await client.get(url: urlComponet!.url!, authToken: authToken)
여기두 위와 동일합니다!

2024-09-08 08:30 UTC, Junu-Park commented on PLAT/PLAT/Network/Service/TrackService.swift
> +struct TrackService {
뭐든 구현할 때 struct와 class 중 찾아본 레퍼런스들에서  많이 나온 것을 따랐는데 이런 고민 좋네요🤔

2024-09-08 09:02 UTC, WooFeather commented on PLAT/PLAT/Network/Service/DTO/NetworkError.swift
> +            return "🥵 URLComponents 오류"
urlComponentsError를 새로 정의해주었습니다.

2024-09-08 09:03 UTC, WooFeather commented on PLAT/PLAT/Network/Service/TrackService.swift
>          }
urlComponent와 url 모두 옵셔널 바인딩 처리를 했습니다.

2024-09-08 09:03 UTC, WooFeather commented on PLAT/PLAT/Network/Service/TrackService.swift
>          }
urlComponent와 url 모두 옵셔널 바인딩 처리를 했습니다.

2024-09-08 09:08 UTC, thinkySide commented on PLAT/PLAT/Network/Service/TrackService.swift
>          }
좋습니당!

2024-09-08 09:08 UTC, thinkySide approved these changes
고생많으셨습니다! 네트워크 연결하면서 서로 공부가 많이 된것 같아엽

2024-09-08 10:19 UTC, merged